### ISSUE TITLE
atsge 1.11.1 fails with python 3

### ISSUE THREAD

**Issue by benkrikler** [shane-breeze/atsge#6]
This line: https://github.com/shane-breeze/atsge/blob/master/atsge/SGEJobSubmitter.py#L143
fails in python 3 because `stdout` and `stderr` are byte strings.   Simply converting to them to strings should work fine for both python2 and 3 and solve this issue.  This seems to be the only problem for Pyhon3 as far as I can see.

**Comment by shane-breeze** [comment]
Does #7 look ok?

**Comment by benkrikler** [comment]
Hey Shane.  I missed that you had fixed things, but the fix does seem to work, as confirmed by @davignon as well.  I think this can be closed then.   

Do you plan on releasing things to Pypi at all? For now we're just installing direct from github with pip if we need SGE.

**Comment by shane-breeze** [comment]
Done. See v0.2.0
