### ISSUE TITLE
v0.2 release to pypi fails for Python 2

### ISSUE THREAD

**Issue by benkrikler** [shane-breeze/atsge#8]
Hey Shane,  thanks for releasing v0.2.0.  I think the deployment to Pypi is broken for python2 though.  I think it's to do with having to build from source, but setup.py points to `requirements.txt` and this isn't shipped for the pypi deployment, e.g. see this job: https://travis-ci.com/FAST-HEP/fast-carpenter/jobs/287890297.

**Comment by shane-breeze** [comment]
I built the wheels with python3 so the python2 version didn't exist so it fellback onto the tarred file which doesn't contain the `requirments.txt` file as you found out. I haven't got much time to fix this properly, but I've uploaded the python2 wheel to the pypi package, so hopefully it picks this up instead and it will work. I've tested it on my side with python2 and it seems to work

**Comment by benkrikler** [comment]
Thank you Shane, that seems to have fixed it!
